general:
  input_path: ../../data/aka_random_forest.csv
  input_columns: [QBaells_Desf,QBalsanery_Desf,QBerga_Desf,QCardona_Desf,QSuria_Desf,Prep_Desf, EC_suriaDesf]
  output_columns: [EC_Abrera]

training:
  test_split_proportion: 0.8
  normalization_scaler_type: MinMaxScaler

validation:
  output_file: "output_report.html"
  initial_data_analysis:
    correlation_matrix: True
